In [83]:
import sys, os
current_dir = os.getcwd()
project_root = current_dir[:current_dir.find("src") - 1]
sys.path.insert(0, project_root)
from src.models.data_selection.data_selector import Data_selector

In [84]:
import pandas as pd
folder_path = os.path.join(project_root, "data", "processed", "integrated.csv")
df_zero = pd.read_csv(folder_path)

In [85]:
folder_path = os.path.join(project_root, "data", "processed", "semi_processed.csv")
df = pd.read_csv(folder_path)

In [87]:
data_set = {"name":[],"code":[],"gi":[],"g0":[],"g1":[],"g2":[],"g3":[],"g4":[],"g5":[],"n_T":[],"n_G":[],"n_S":[]}
ds = Data_selector(df)
ds_zero = Data_selector(df_zero)
for _,row in df_zero[["name","code"]].drop_duplicates().iterrows():
    name = row["name"]
    code = row["code"]
    data_set["name"].append(name)
    data_set["code"].append(code)
    unit_ds = Data_selector(ds.filter_name_code(name,code))
    
    df_zero_filtered = ds_zero.filter_name_code(name,code)
    ll = len(df_zero_filtered)
    data_set["gi"].append(ll)
    data_set["n_T"].append(int(100*df_zero_filtered['temperature'].isnull().sum()/ll))
    data_set["n_S"].append(int(100*(df_zero_filtered['scadaf'].isnull() | df_zero_filtered['temp_sens'].isnull()).sum()/ll))
    data_set["n_G"].append(int(100*df_zero_filtered['generation'].isnull().sum()/ll))
    
    for goodness in range(0,6):
        gx = f"g{goodness}"
        l = len(unit_ds.select_peaks(goodness))
        data_set[gx].append(int((l/ll)*100))

In [88]:
df_data = pd.DataFrame(data_set)

In [89]:
df_data["H1"] = df_data["n_T"] + df_data["g0"]

In [90]:
df_data[df_data["code"].str.startswith("G")]

                   name code     gi  g0  g1  g2  g3  g4  g5  n_T  n_G  n_S  H1
0                  پرند  G13  12480  99  38  18   7   7   5    0    0   10  99
2                  پرند  G15  12480  99  36  17   8   8   5    0    0   10  99
3                  پرند  G14  12480  99  37  16   7   7   5    0    0   10  99
5                  پرند  G12  12480  99  37  23   8   4   3    0    0   10  99
6                  پرند  G11  35208  97  33  18   8   7   5    0    1   28  97
..                  ...  ...    ...  ..  ..  ..  ..  ..  ..  ...  ...  ...  ..
101                حافظ  G13  12480  99  37  20   7   7   5    0    0   53  99
102              عسلویه  G11  35208  97  32  23  12  10   4    0    1   16  97
103                حافظ  G12  12480  99  38  21   8   8   7    0    0   53  99
104  سیکل ترکیبی شیروان  G12  12480  99  36  14   5   5   1    0    0   20  99
106                حافظ  G11  35208  97  33  17   7   7   4    0    1   49  97

[72 rows x 13 columns]

In [75]:
df_data

                   name code     gi  g0  g1  g2  g3  g4  g5  n_T  n_G  n_S  H1
0                  پرند  G13  12480  89  35  16  10  10   9    8    0   10  99
2                  پرند  G15  12480  89  33  15  11  11   9    8    0   10  99
3                  پرند  G14  12480  89  34  15  11  11   8    8    0   10  99
5                  پرند  G12  12480  89  33  20  14   6   5    8    0   10  99
6                  پرند  G11  35208  69  20  11   7   4   3   27    1   28  97
..                  ...  ...    ...  ..  ..  ..  ..  ..  ..  ...  ...  ...  ..
101                حافظ  G13  12480  46  16   9   7   1   0   52    0   53  99
102              عسلویه  G11  35208  81  25  18  10   4   1   15    1   16  97
103                حافظ  G12  12480  46  17   9   7   1   0   52    0   53  99
104  سیکل ترکیبی شیروان  G12  12480  78  26  10   5   1   1    4    0   20  98
106                حافظ  G11  35208  49  16   8   5   3   1   48    1   49  98

[72 rows x 13 columns]

In [62]:
df_bad = df_data[df_data["H1"]<95]

In [63]:
df_bad

                      name code     gi  g0  g1  g2  g3  g4  g5  n_T  n_G  H1
10   شهدای پاکدشت - دماوند  G16  12480  62  21   9   2   2   1   13    0  75
11   شهدای پاکدشت - دماوند  G11  35208  61  18   7   1   0   0   29    2  90
13   شهدای پاکدشت - دماوند  G13  12480  62  21  10   2   1   0   13    0  75
14   شهدای پاکدشت - دماوند  G17  12480  62  21   8   2   2   1   13    0  75
17   شهدای پاکدشت - دماوند  G14  12480  62  21   8   2   2   0   13    0  75
18   شهدای پاکدشت - دماوند  G21  12480  62  22  10   2   1   0   13    0  75
19   شهدای پاکدشت - دماوند  G20  12480  62  19   7   1   1   0   13    0  75
20   شهدای پاکدشت - دماوند  G15  12480  62  21   8   1   1   1   13    0  75
21   شهدای پاکدشت - دماوند  G22  12480  62  18   7   2   2   1   13    0  75
22   شهدای پاکدشت - دماوند  G12  12480  62  22   8   1   1   0   13    0  75
24   شهدای پاکدشت - دماوند  G19  12480  62  21   8   2   2   1   13    0  75
25   شهدای پاکدشت - دماوند  G18  12480  62  22   9   2   0   0   13    0  75
42    شهدای پیروز - بهبهان  G12  12480  83  29  21  18  18  16   11    0  94
57                   سبلان  G13  12480  41  11   5   4   4   4    5    0  46
58                   سبلان  G16  12480  41  18  10   6   6   5    5    0  46
59                   سبلان  G12  12480  41  18  10   5   5   5    5    0  46
60                   سبلان  G15  12480  41  19  10   6   6   6    5    0  46
61                   سبلان  G14  12480  41  18  11   9   9   9    5    0  46
62                   سبلان  G11  35208  53  16   9   6   4   3    5    1  58
65      سیکل ترکیبی ارومیه  G12  12480  75  23  17  10  10   8    2    0  77
67      سیکل ترکیبی ارومیه  G11  35208  82  21  14   7   4   2    2    1  84
69      سیکل ترکیبی ارومیه  G14  12480  75  23  13   5   5   4    2    0  77
70      سیکل ترکیبی ارومیه  G13  12480  75  22  13   6   6   5    2    0  77
81      سیکل ترکیبی شیروان  G16  12480  78  24   9   5   5   1    4    0  82
83      سیکل ترکیبی شیروان  G14  12480  78  26  10   5   5   1    4    0  82
84      سیکل ترکیبی شیروان  G11  35208  88  27  10   4   4   0    3    1  91
85      سیکل ترکیبی شیروان  G15  12480  78  23   7   4   4   1    4    0  82
87      سیکل ترکیبی شیروان  G13  12480  78  26  10   4   4   1    4    0  82
88      سیکل ترکیبی ارومیه  G15  12480  75  22  12   6   6   5    2    0  77
89      سیکل ترکیبی ارومیه  G16  12480  75  22  13   7   7   5    2    0  77
104     سیکل ترکیبی شیروان  G12  12480  78  26  10   5   1   1    4    0  82

In [53]:
 df_data["n_T"]+df_data["g0"]

0      97
1       8
2      97
3      97
4       8
       ..
103    98
104    82
105     2
106    97
107     4
Length: 108, dtype: int64

In [64]:
data_set = {"name":[],"code":[],"gi":[],"g0":[],"g1":[],"g2":[],"g3":[],"g4":[],"g5":[],"n_T":[],"n_G":[]}
ds = Data_selector(df_bad)
for _,row in df_bad[["name","code"]].drop_duplicates().iterrows():
    name = row["name"]
    code = row["code"]

                      name code     gi  g0  g1  g2  g3  g4  g5  n_T  n_G  H1
10   شهدای پاکدشت - دماوند  G16  12480  62  21   9   2   2   1   13    0  75
11   شهدای پاکدشت - دماوند  G11  35208  61  18   7   1   0   0   29    2  90
13   شهدای پاکدشت - دماوند  G13  12480  62  21  10   2   1   0   13    0  75
14   شهدای پاکدشت - دماوند  G17  12480  62  21   8   2   2   1   13    0  75
17   شهدای پاکدشت - دماوند  G14  12480  62  21   8   2   2   0   13    0  75
18   شهدای پاکدشت - دماوند  G21  12480  62  22  10   2   1   0   13    0  75
19   شهدای پاکدشت - دماوند  G20  12480  62  19   7   1   1   0   13    0  75
20   شهدای پاکدشت - دماوند  G15  12480  62  21   8   1   1   1   13    0  75
21   شهدای پاکدشت - دماوند  G22  12480  62  18   7   2   2   1   13    0  75
22   شهدای پاکدشت - دماوند  G12  12480  62  22   8   1   1   0   13    0  75
24   شهدای پاکدشت - دماوند  G19  12480  62  21   8   2   2   1   13    0  75
25   شهدای پاکدشت - دماوند  G18  12480  62  22   9   2   0   0   13    0  75
42    شهدای پیروز - بهبهان  G12  12480  83  29  21  18  18  16   11    0  94
57                   سبلان  G13  12480  41  11   5   4   4   4    5    0  46
58                   سبلان  G16  12480  41  18  10   6   6   5    5    0  46
59                   سبلان  G12  12480  41  18  10   5   5   5    5    0  46
60                   سبلان  G15  12480  41  19  10   6   6   6    5    0  46
61                   سبلان  G14  12480  41  18  11   9   9   9    5    0  46
62                   سبلان  G11  35208  53  16   9   6   4   3    5    1  58
65      سیکل ترکیبی ارومیه  G12  12480  75  23  17  10  10   8    2    0  77
67      سیکل ترکیبی ارومیه  G11  35208  82  21  14   7   4   2    2    1  84
69      سیکل ترکیبی ارومیه  G14  12480  75  23  13   5   5   4    2    0  77
70      سیکل ترکیبی ارومیه  G13  12480  75  22  13   6   6   5    2    0  77
81      سیکل ترکیبی شیروان  G16  12480  78  24   9   5   5   1    4    0  82
83      سیکل ترکیبی شیروان  G14  12480  78  26  10   5   5   1    4    0  82
84      سیکل ترکیبی شیروان  G11  35208  88  27  10   4   4   0    3    1  91
85      سیکل ترکیبی شیروان  G15  12480  78  23   7   4   4   1    4    0  82
87      سیکل ترکیبی شیروان  G13  12480  78  26  10   4   4   1    4    0  82
88      سیکل ترکیبی ارومیه  G15  12480  75  22  12   6   6   5    2    0  77
89      سیکل ترکیبی ارومیه  G16  12480  75  22  13   7   7   5    2    0  77
104     سیکل ترکیبی شیروان  G12  12480  78  26  10   5   1   1    4    0  82

In [65]:
def get_null(df, df_name_code):
    infos = []
    for _, row in df_name_code.iterrows():
        name = row["name"]
        code = row["code"]
        unit = Data_selector(df).filter_name_code(name, code)
        g = (unit.isnull().sum() / len(unit)).astype(object)
        g.loc["name"] = name
        g.loc["code"] = code
        infos.append(g)
    df_infos = pd.DataFrame(infos)

    drop_cols = []
    for col in df_infos.columns:
        try:
            m = sum(df_infos[col])
            if m == 0:
                print(col)
                drop_cols.append(col)
        except:
            pass
    df_infos2 = df_infos.drop(columns=drop_cols)
    df_infos2.columns[(df_infos2 == 1).all()]

    return df_infos2

In [67]:
get_null(df_zero, df_bad[["name","code"]])

id
date
hour
load_level
forecasted_load
required
status
evapotranspiration

,name,code,declared,generation,temp_sens,scadaf,temperature,humidity,dew,apparent_temperature,precipitation,rain,snow,surface_pressure,wind_speed,wind_direction
0,شهدای پاکدشت - دماوند,G16,0.000000,0.001923,0.131330,0.252965,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
1,شهدای پاکدشت - دماوند,G11,0.000682,0.023177,0.296154,0.093388,0.001449,0.001449,0.001449,0.001449,0.001477,0.001477,0.001477,0.001449,0.001449,0.001449
2,شهدای پاکدشت - دماوند,G13,0.000000,0.001923,0.131330,0.252965,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
3,شهدای پاکدشت - دماوند,G17,0.000000,0.001923,0.131330,0.252965,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
4,شهدای پاکدشت - دماوند,G14,0.000000,0.001923,0.131330,0.252965,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
5,شهدای پاکدشت - دماوند,G21,0.000000,0.001923,0.131330,0.252965,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
6,شهدای پاکدشت - دماوند,G20,0.000000,0.001923,0.131330,0.252965,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
7,شهدای پاکدشت - دماوند,G15,0.000000,0.001923,0.131330,0.252965,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
8,شهدای پاکدشت - دماوند,G22,0.000000,0.001923,0.131330,0.252965,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
9,شهدای پاکدشت - دماوند,G12,0.000000,0.001923,0.131330,0.252965,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
10,شهدای پاکدشت - دماوند,G19,0.000000,0.001923,0.131330,0.252965,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
11,شهدای پاکدشت - دماوند,G18,0.000000,0.001923,0.131330,0.252965,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
12,شهدای پیروز - بهبهان,G12,0.000000,0.001923,0.117548,0.039022,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
13,سبلان,G13,0.001923,0.001923,0.050160,0.563061,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
14,سبلان,G16,0.001923,0.001923,0.050160,0.563061,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
15,سبلان,G12,0.001923,0.001923,0.050160,0.563061,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
16,سبلان,G15,0.001923,0.001923,0.050160,0.563061,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
17,سبلان,G14,0.001923,0.001923,0.050160,0.563061,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
18,سبلان,G11,0.000682,0.019087,0.059958,0.413372,0.001449,0.001449,0.001449,0.001449,0.001477,0.001477,0.001477,0.001449,0.001449,0.001449
19,سیکل ترکیبی ارومیه,G12,0.000000,0.001923,0.026522,0.213381,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
20,سیکل ترکیبی ارومیه,G11,0.000000,0.019087,0.024398,0.132413,0.001449,0.001449,0.001449,0.001449,0.001477,0.001477,0.001477,0.001449,0.001449,0.001449
21,سیکل ترکیبی ارومیه,G14,0.000000,0.001923,0.026522,0.213381,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
22,سیکل ترکیبی ارومیه,G13,0.000000,0.001923,0.026522,0.213381,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
23,سیکل ترکیبی شیروان,G16,0.000000,0.001923,0.049119,0.176042,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
24,سیکل ترکیبی شیروان,G14,0.000000,0.001923,0.049119,0.176042,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
25,سیکل ترکیبی شیروان,G11,0.000000,0.019087,0.032493,0.073648,0.001449,0.001449,0.001449,0.001449,0.001477,0.001477,0.001477,0.001449,0.001449,0.001449
26,سیکل ترکیبی شیروان,G15,0.000000,0.001923,0.049119,0.176042,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
27,سیکل ترکیبی شیروان,G13,0.000000,0.001923,0.049119,0.176042,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
28,سیکل ترکیبی ارومیه,G15,0.000000,0.001923,0.026522,0.213381,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
29,سیکل ترکیبی ارومیه,G16,0.000000,0.001923,0.026522,0.213381,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087
30,سیکل ترکیبی شیروان,G12,0.000000,0.001923,0.049119,0.176042,0.004087,0.004087,0.004087,0.004087,0.004167,0.004167,0.004167,0.004087,0.004087,0.004087