In [1]:
import sys, os
current_dir = os.getcwd()
project_root = current_dir[:current_dir.find("src") - 1]
sys.path.insert(0, project_root)
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
from src.models.train_model.train_model import *

In [253]:
df_old      = pd.read_csv(os.path.join(project_root, "data", "processed", "integrated.csv"))
df_new      = pd.read_csv(os.path.join(project_root, "data", "processed", "semi_processed.csv"))
df_energy   = pd.read_csv(os.path.join(project_root, "data", "interim", "energy.csv"))
df_commitment= pd.read_csv(os.path.join(project_root, "data", "interim", "commitment.csv"))
df_factors  = pd.read_csv(os.path.join(project_root, "data", "interim", "factors.csv"))
df_weather  = pd.read_csv(os.path.join(project_root, "data", "interim", "weather.csv"))
df_selleroffer      = pd.read_csv(os.path.join(project_root, "data", "interim", "selleroffer.csv"))

In [254]:
def set_minus(df1,df2,column=None):
    if column == None:
        column = df1.columns.to_list()
    merged = df1.merge(df2, on=column, how='left', indicator=True)
    result = merged[merged['_merge'] == 'left_only'].drop('_merge', axis=1)
    return result
def equals(df1,df2):
    return set_minus(df1,df2).empty and set_minus(df2,df1).empty

In [255]:
def delete_C(df):
    df1 = df.copy()
    df1["code_e"] = df1["code"].copy()
    df1["code"] = df1["code"].apply(lambda x: x[1:] if x.startswith("C") else x)
    return df1

In [256]:
print(equals(df_old[["id","code"]].drop_duplicates(),delete_C(df_energy)[["id","code"]].drop_duplicates()))

False

In [257]:
set_minus(delete_C(df_energy)[["id","code","code_e"]].drop_duplicates(),df_new[["id","code"]].drop_duplicates(),column = ["id","code"])

     id code code_e
0   104   S1    CS1
1   104   S2    CS2
2   104   S3    CS3
9   111  G11   CG11
10  111  G12   CG12
11  111  G13   CG13
12  111  G14   CG14
13  111  G15   CG15
14  111  G16   CG16
15  111  G17   CG17
16  111  G18   CG18
17  111  G19   CG19
18  111  G20   CG20
19  111  G21   CG21
20  111  G22   CG22
21  111   S1    CS1
22  111   S2    CS2
23  111   S3    CS3
24  111   S4    CS4
25  111   S5    CS5
26  111   S6    CS6
27  149  G11   CG11
28  149  G12   CG12
29  149  G13   CG13
30  149  G14   CG14
31  149   S1    CS1
32  149   S2    CS2
33  232  G11   CG11
34  232  G12   CG12
35  232  G13   CG13
36  232  G14   CG14
37  232  G15   CG15
38  232  G16   CG16
39  232   S1    CS1
40  232   S2    CS2
41  232   S3    CS3
44  365  G13    G13
45  365  G14    G14
47  365   S2     S2
61  515   S1    CS1
68  636  G13   CG13
69  636  G14   CG14
70  636  G15   CG15
71  636  G16   CG16
72  636   S1    CS1
73  636   S2    CS2

In [271]:
set_minus(df_new[["id","code"]].drop_duplicates(),delete_C(df_energy)[["id","code","code_e"]].drop_duplicates(),column = ["id","code"])

Empty DataFrame
Columns: [id, code, code_e]
Index: []

In [274]:
set_minus(delete_C(df_energy)[["id","code","name"]].drop_duplicates(),df_old[["id","code"]].drop_duplicates(),column = ["id","code"])

     id code                     name
44  365  G13  سيکل ترکيبي شهداي پيروز
45  365  G14  سيکل ترکيبي شهداي پيروز
47  365   S2  سيکل ترکيبي شهداي پيروز

just in df_energy()
	id	code	name
44	365	G13	سيکل ترکيبي شهداي پيروز
45	365	G14	سيکل ترکيبي شهداي پيروز
47	365	S2	سيکل ترکيبي شهداي پيروز

In [279]:
df_energy.head()

    id code              name        date  hour  generation
0  104  CS1  سيکل ترکيبي پرند  2021-03-21     1  129.671081
1  104  CS1  سيکل ترکيبي پرند  2021-03-22     1    0.000000
2  104  CS1  سيکل ترکيبي پرند  2021-03-23     1  150.046121
3  104  CS1  سيکل ترکيبي پرند  2021-03-24     1  136.338788
4  104  CS1  سيکل ترکيبي پرند  2021-03-25     1  139.025321

In [287]:
len(df_energy[(df_energy["code"] == "G11") & (df_energy["id"]==917)])/24

1433.0

In [260]:
set_minus(df_old[["id","code","name"]].drop_duplicates(),delete_C(df_energy)[["id","code"]].drop_duplicates(),column = ["id","code"])

      id code                name
17   422   S4       شهید منتظری 1
18   422   S3       شهید منتظری 1
19   422   S5       شهید منتظری 1
53   422   S7       شهید منتظری 1
54   422   S1       شهید منتظری 1
55   422   S6       شهید منتظری 1
68   422   S8       شهید منتظری 1
78   422   S2       شهید منتظری 1
103  515   S2  سیکل ترکیبی ارومیه
104  902   S2              عسلویه
105  503   S2               سبلان
106  503   S3               سبلان
107  515   S3  سیکل ترکیبی ارومیه

In [261]:
df_selleroffer[["id","name","code"]][df_selleroffer["id"] == 365].drop_duplicates()

          id                  name code
1472288  365  شهدای پیروز - بهبهان  G11
1507784  365  شهدای پیروز - بهبهان  G12
1543281  365  شهدای پیروز - بهبهان   S1

In [262]:
set_minus(df_old[["id","code"]].drop_duplicates(),df_commitment[["id","code"]].drop_duplicates(),column = ["id","code"])

Empty DataFrame
Columns: [id, code]
Index: []

In [263]:
set_minus(df_commitment[["id","code"]].drop_duplicates(),df_old[["id","code"]].drop_duplicates(),column = ["id","code"])

Empty DataFrame
Columns: [id, code]
Index: []

In [264]:
df_weather2 = df_weather.rename(columns={"unitid":"id"})
set_minus(df_old[["id"]].drop_duplicates(),df_weather2[["id"]].drop_duplicates())

Empty DataFrame
Columns: [id]
Index: []

In [265]:
set_minus(df_weather2[["id"]].drop_duplicates(),df_old[["id"]].drop_duplicates())

Empty DataFrame
Columns: [id]
Index: []

In [266]:
df_selleroffer.head()

    id  name code        date  hour  declare
0  104  پرند  G11  2021-03-21     1    132.0
1  104  پرند  G11  2021-03-21     2    132.0
2  104  پرند  G11  2021-03-21     3    132.0
3  104  پرند  G11  2021-03-21     4    132.0
4  104  پرند  G11  2021-03-21     5    133.0

In [267]:
set_minus(df_old[["id","code"]].drop_duplicates(),df_selleroffer[["id","code"]].drop_duplicates()) # old = energy + 422

Empty DataFrame
Columns: [id, code]
Index: []

In [268]:
set_minus(df_selleroffer[["id","code"]].drop_duplicates(),df_old[["id","code"]].drop_duplicates()) # old = energy + 422

Empty DataFrame
Columns: [id, code]
Index: []

In [120]:
def get_null(df,df_name_code):
    infos = []
    for _,row in df_name_code.iterrows():
        name = row["name"]
        code = row["code"]
        inf = Data_selector(df).filter_name_code(name,code)
        g = (inf.isnull().sum()/len(inf)).astype(object)
        g.loc["name"] = name
        g.loc["code"] = code
        infos.append(g)
    df_infos = pd.DataFrame(infos)
    
    drop_cols = []
    for col in df_infos.columns:
        try:
            m = sum(df_infos[col])
            #print(col,m)
            if m == 0:
                print(col)
                drop_cols.append(col)
        except:
            pass
            #print(col)
    df_infos2 = df_infos.drop(columns=drop_cols)
    df_infos2.columns[(df_infos2 == 1).all()]

    return df_infos2

In [122]:
get_null(df_old,df_old_name_code)

id
date
hour
load_level
forecasted_load
required
wind_speed

,name,code,declared,status,generation,temp_sens,scadaf,temperature,humidity,dew,apparent_temperature,precipitation,rain,snow,surface_pressure,evapotranspiration,wind_direction
0,پرند,G12,0.000000,0.0,0.001923,0.100641,0.100641,0.004087,0.004087,0.004087,0.004087,1.0,0.004167,0.004167,0.004167,0.004087,0.004087
1,پرند,S1,0.000000,0.0,1.000000,0.100641,0.100641,0.004087,0.004087,0.004087,0.004087,1.0,0.004167,0.004167,0.004167,0.004087,0.004087
2,پرند,S3,0.000000,0.0,1.000000,0.100641,0.100641,0.004087,0.004087,0.004087,0.004087,1.0,0.004167,0.004167,0.004167,0.004087,0.004087
3,پرند,G13,0.000000,0.0,0.001923,0.100641,0.100641,0.004087,0.004087,0.004087,0.004087,1.0,0.004167,0.004167,0.004167,0.004087,0.004087
4,پرند,G15,0.000000,0.0,0.001923,0.100641,0.100641,0.004087,0.004087,0.004087,0.004087,1.0,0.004167,0.004167,0.004167,0.004087,0.004087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,سیکل ترکیبی ارومیه,S2,0.573394,0.0,1.000000,0.526376,0.526376,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
104,عسلویه,S2,1.000000,0.0,1.000000,0.051418,0.051418,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
105,سبلان,S2,1.000000,0.0,1.000000,0.847518,0.847518,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
106,سبلان,S3,1.000000,0.0,1.000000,0.662946,0.662946,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
107,سیکل ترکیبی ارومیه,S3,1.000000,0.0,1.000000,0.039062,0.039062,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000

In [123]:
def is_bigger(a,b1,b2):
    try:
        return a >= b1 and a <= b2
    except:
        return False
print("خانه‌هایی با مقدار 1:")
for index, row in df_infos2.iterrows():
    ones_in_row = []
    for col in df_infos2.columns:
        if col not in ['name', 'id'] and is_bigger(row[col],1,1):
            ones_in_row.append(col)
    
    if ones_in_row:
        print(f"{row['name']} {(22 - len(row['name']))*' '} {row['code']}, ستون‌ها: {', '.join(ones_in_row)}")

خانه‌هایی با مقدار 1:
پرند                    S1, ستون‌ها: generation, precipitation
پرند                    S3, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G16, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   S3, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   S2, ستون‌ها: generation, precipitation
قم                      G13, ستون‌ها: generation, precipitation
قم                      G12, ستون‌ها: generation, precipitation
گیلان                   G14, ستون‌ها: generation, precipitation
گیلان                   G13, ستون‌ها: generation, precipitation
گیلان                   G15, ستون‌ها: generation, precipitation
شهید منتظری 1           S4, ستون‌ها: generation, precipitation
شهید منتظری 1           S3, ستون‌ها: generation, precipitation
شهید منتظری 1           S5, ستون‌ها: generation, precipitation
سیکل ترکیبی ارومیه      S1, ستون‌ها: generation, precipitation
سیکل ترکیبی یزد         G14, ستون‌ها: generation, precipitation
سیکل ترکیبی یزد         G15, ستون‌ها: generation, precipitation
سیکل ترکیبی یزد         G13, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   S6, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G11, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G15, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G17, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G14, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   S4, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G21, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G18, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G13, ستون‌ها: generation, precipitation
قم                      G11, ستون‌ها: generation, precipitation
قم                      S1, ستون‌ها: generation, precipitation
قم                      G14, ستون‌ها: generation, precipitation
گیلان                   S1, ستون‌ها: generation, precipitation
گیلان                   G16, ستون‌ها: generation, precipitation
گیلان                   S2, ستون‌ها: generation, precipitation
شهید منتظری 1           S7, ستون‌ها: generation, precipitation
شهید منتظری 1           S1, ستون‌ها: generation, precipitation
شهید منتظری 1           S6, ستون‌ها: generation, precipitation
سیکل ترکیبی یزد         S1, ستون‌ها: generation, precipitation
سیکل ترکیبی یزد         S2, ستون‌ها: generation, precipitation
شهید منتظری 1           S8, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   S1, ستون‌ها: generation, precipitation
پرند                    S2, ستون‌ها: generation, precipitation
شهید منتظری 1           S2, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G22, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G19, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G12, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G20, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   S5, ستون‌ها: generation, precipitation
قم                      S2, ستون‌ها: generation, precipitation
گیلان                   G12, ستون‌ها: generation, precipitation
گیلان                   G11, ستون‌ها: generation, precipitation
گیلان                   S3, ستون‌ها: generation, precipitation
سیکل ترکیبی یزد         G16, ستون‌ها: generation, precipitation
سیکل ترکیبی ارومیه      S2, ستون‌ها: generation, precipitation
عسلویه                  S2, ستون‌ها: declared, generation, precipitation
سبلان                   S2, ستون‌ها: declared, generation, precipitation
سبلان                   S3, ستون‌ها: declared, generation, precipitation
سیکل ترکیبی ارومیه      S3, ستون‌ها: declared, generation, precipitation

In [249]:
df_energy_name_code[["name","code"]].drop_duplicates()

                    name code
0       سيکل ترکيبي پرند   S1
1433    سيکل ترکيبي پرند   S2
2866    سيکل ترکيبي پرند   S3
4299    سيکل ترکيبي پرند  G11
5732    سيکل ترکيبي پرند  G12
...                  ...  ...
130727  سيکل ترکيبي حافظ  G12
132160  سيکل ترکيبي حافظ  G13
133593  سيکل ترکيبي حافظ  G14
135026  سيکل ترکيبي حافظ  G15
136459  سيکل ترکيبي حافظ  G16

[98 rows x 2 columns]

In [251]:
delete_C(df_energy)

          id code              name        date  hour  generation code_e
0        104   S1  سيکل ترکيبي پرند  2021-03-21     1  129.671081     S1
1        104   S1  سيکل ترکيبي پرند  2021-03-22     1    0.000000     S1
2        104   S1  سيکل ترکيبي پرند  2021-03-23     1  150.046121     S1
3        104   S1  سيکل ترکيبي پرند  2021-03-24     1  136.338788     S1
4        104   S1  سيکل ترکيبي پرند  2021-03-25     1  139.025321     S1
...      ...  ...               ...         ...   ...         ...    ...
3309403  917  G16  سيکل ترکيبي حافظ  2025-02-20    24   48.907920    G16
3309404  917  G16  سيکل ترکيبي حافظ  2025-02-21    24    0.000000    G16
3309405  917  G16  سيکل ترکيبي حافظ  2025-02-22    24  122.459420    G16
3309406  917  G16  سيکل ترکيبي حافظ  2025-02-23    24   86.027730    G16
3309407  917  G16  سيکل ترکيبي حافظ  2025-02-24    24   91.663740    G16

[3309408 rows x 7 columns]

In [235]:
delete_C(df_energy_name_code)[["name","code"]].drop_duplicates()

                    name code
0       سيکل ترکيبي پرند   S1
1433    سيکل ترکيبي پرند   S2
2866    سيکل ترکيبي پرند   S3
4299    سيکل ترکيبي پرند  G11
5732    سيکل ترکيبي پرند  G12
...                  ...  ...
130727  سيکل ترکيبي حافظ  G12
132160  سيکل ترکيبي حافظ  G13
133593  سيکل ترکيبي حافظ  G14
135026  سيکل ترکيبي حافظ  G15
136459  سيکل ترکيبي حافظ  G16

[98 rows x 2 columns]

In [246]:
df_energy_name_code

                    name code code_e
0       سيکل ترکيبي پرند   S1     S1
1433    سيکل ترکيبي پرند   S2     S2
2866    سيکل ترکيبي پرند   S3     S3
4299    سيکل ترکيبي پرند  G11    G11
5732    سيکل ترکيبي پرند  G12    G12
...                  ...  ...    ...
130727  سيکل ترکيبي حافظ  G12    G12
132160  سيکل ترکيبي حافظ  G13    G13
133593  سيکل ترکيبي حافظ  G14    G14
135026  سيکل ترکيبي حافظ  G15    G15
136459  سيکل ترکيبي حافظ  G16    G16

[98 rows x 3 columns]

In [245]:
df_energy["code_e"].drop_duplicates()

0         S1
1433      S2
2866      S3
4299     G11
5732     G12
7165     G13
8598     G14
10031    G15
11464    G16
21459    G17
22885    G18
24308    G19
25735    G20
27161    G21
28588    G22
34294     S4
35720     S5
37147     S6
Name: code_e, dtype: object

In [243]:
df_energy["code_e"]

0           S1
1           S1
2           S1
3           S1
4           S1
          ...
3309403    G16
3309404    G16
3309405    G16
3309406    G16
3309407    G16
Name: code_e, Length: 3309408, dtype: object