In [ ]:
import os
import sys

current_dir = os.getcwd()
project_root = current_dir[:current_dir.find("src") - 1]
sys.path.insert(0, project_root)
from src.models.train_model.train_model import *

In [25]:
df_old = pd.read_csv(os.path.join(project_root, "data", "processed", "integrated.csv"))
df_new = pd.read_csv(os.path.join(project_root, "data", "processed", "semi_processed.csv"))
df_energy = pd.read_csv(os.path.join(project_root, "data", "interim", "energy.csv"))
df_commitment = pd.read_csv(os.path.join(project_root, "data", "interim", "commitment.csv"))
df_factors = pd.read_csv(os.path.join(project_root, "data", "interim", "factors.csv"))
df_weather = pd.read_csv(os.path.join(project_root, "data", "interim", "weather.csv"))
df_selleroffer = pd.read_csv(os.path.join(project_root, "data", "interim", "selleroffer.csv"))

In [37]:
df_temp = pd.read_csv(os.path.join(project_root, "data", "interim", "plant_temp.csv"))

In [42]:
df_temp

        PowerPlantCode PowerPlantName        Date  HourNo  SCADAF  TempSens
0                  104           پرند  2021-03-21       1   11.38     12.97
1                  104           پرند  2021-03-21       2   10.32      9.36
2                  104           پرند  2021-03-21       3   11.02     11.95
3                  104           پرند  2021-03-21       4    8.26      8.93
4                  104           پرند  2021-03-21       5    9.90      8.47
...                ...            ...         ...     ...     ...       ...
294624             917           حافظ  2025-03-17       5   13.56     12.48
294625             917           حافظ  2025-03-17       6   13.13     12.17
294626             917           حافظ  2025-03-17       7   12.92     11.17
294627             917           حافظ  2025-03-17       8   17.77     12.77
294628             917           حافظ  2025-03-17       9   18.26     15.81

[294629 rows x 6 columns]

In [41]:
df_old[["id"]].drop_duplicates()

          id
0        104
130649   111
353467   149
418628   232
540542   365
605854   406
713403   422
806345   503
896692   515
980618   636
1076489  715
1203897  902
1292411  917

In [43]:
df_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1590288 entries, 0 to 1590287
Data columns (total 24 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1590288 non-null  int64
 1   name                  1590288 non-null  object
 2   code                  1590288 non-null  object
 3   date                  1590288 non-null  object
 4   hour                  1590288 non-null  int64
 5   load_level            1590288 non-null  object
 6   forecasted_load       1590288 non-null  int64
 7   required              1590288 non-null  float64
 8   declared              1570704 non-null  float64
 9   status                1590206 non-null  object
 10  generation            1436016 non-null  float64
 11  temp_sens             1054454 non-null  float64
 12  scadaf                1054454 non-null  float64
 13  temperature           1585188 non-null  float64
 14  humidity              1585188 non-null  float64
 15  dew                   1585188 non-null  float64
 16  apparent_temperature  1585188 non-null  float64
 17  precipitation         1585088 non-null  float64
 18  rain                  1585088 non-null  float64
 19  snow                  1585088 non-null  float64
 20  surface_pressure      1585188 non-null  float64
 21  evapotranspiration    1590288 non-null  float64
 22  wind_speed            1585188 non-null  float64
 23  wind_direction        1585188 non-null  float64
dtypes: float64(16), int64(3), object(5)
memory usage: 291.2+ MB

In [50]:
non_nullable_features = ["name", "code", "date", "hour", "load_level", "status", "generation", "temp_sens", "scadaf"]
df1 = df_old.dropna(subset=non_nullable_features)
df2 = df_old.dropna()

In [51]:
df1

,id,name,code,date,hour,load_level,forecasted_load,required,declared,status,...,humidity,dew,apparent_temperature,precipitation,rain,snow,surface_pressure,evapotranspiration,wind_speed,wind_direction
0,104,پرند,G12,2021-03-21,1,L,29288,131.999,132.0,SO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
1,104,پرند,G13,2021-03-21,1,L,29288,0.000,157.0,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
2,104,پرند,G11,2021-03-21,1,L,29288,131.999,132.0,SO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
3,104,پرند,G12,2021-03-21,2,L,28138,132.999,133.0,SO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
4,104,پرند,G11,2021-03-21,2,L,28138,131.998,132.0,SO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1590272,917,حافظ,G14,2022-08-22,15,P,57386,113.999,114.0,LF1,...,9.0,-3.483515,32.190450,0.0,0.0,0.0,842.58734,0.0,5.623380,50.194473
1590273,917,حافظ,G14,2022-08-22,16,P,57764,113.000,113.0,LF1,...,9.0,-3.333768,31.450058,0.0,0.0,0.0,842.50840,0.0,5.351785,42.273630
1590274,917,حافظ,G14,2022-08-22,17,P,57846,111.999,112.0,LF1,...,9.0,-3.333768,30.847427,0.0,0.0,0.0,842.67755,0.0,3.826853,48.814175
1590275,917,حافظ,G14,2022-08-22,18,P,57141,113.000,113.0,LF1,...,9.0,-3.483515,30.473064,0.0,0.0,0.0,842.75653,0.0,4.896529,107.102810
1590276,917,حافظ,G14,2022-08-22,19,M,55425,113.999,114.0,LF1,...,12.0,-0.340241,29.552181,0.0,0.0,0.0,843.14820,0.0,7.289444,159.775050

In [49]:
df2

,id,name,code,date,hour,load_level,forecasted_load,required,declared,status,...,humidity,dew,apparent_temperature,precipitation,rain,snow,surface_pressure,evapotranspiration,wind_speed,wind_direction
156,104,پرند,G13,2021-03-23,5,L,27225,69.996,158.0,R,...,35.0,-0.942513,9.380728,0.0,0.0,0.0,891.10114,0.0,18.391737,310.236270
157,104,پرند,G12,2021-03-23,5,L,27225,108.628,134.0,LF1,...,35.0,-0.942513,9.380728,0.0,0.0,0.0,891.10114,0.0,18.391737,310.236270
158,104,پرند,G11,2021-03-23,5,L,27225,107.817,133.0,LF1,...,35.0,-0.942513,9.380728,0.0,0.0,0.0,891.10114,0.0,18.391737,310.236270
159,104,پرند,G13,2021-03-23,6,L,27095,69.996,160.0,R,...,36.0,-1.044726,8.816505,0.0,0.0,0.0,891.50470,0.0,18.388212,293.051330
160,104,پرند,G11,2021-03-23,6,L,27095,107.988,134.0,LF1,...,36.0,-1.044726,8.816505,0.0,0.0,0.0,891.50470,0.0,18.388212,293.051330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1590272,917,حافظ,G14,2022-08-22,15,P,57386,113.999,114.0,LF1,...,9.0,-3.483515,32.190450,0.0,0.0,0.0,842.58734,0.0,5.623380,50.194473
1590273,917,حافظ,G14,2022-08-22,16,P,57764,113.000,113.0,LF1,...,9.0,-3.333768,31.450058,0.0,0.0,0.0,842.50840,0.0,5.351785,42.273630
1590274,917,حافظ,G14,2022-08-22,17,P,57846,111.999,112.0,LF1,...,9.0,-3.333768,30.847427,0.0,0.0,0.0,842.67755,0.0,3.826853,48.814175
1590275,917,حافظ,G14,2022-08-22,18,P,57141,113.000,113.0,LF1,...,9.0,-3.483515,30.473064,0.0,0.0,0.0,842.75653,0.0,4.896529,107.102810
1590276,917,حافظ,G14,2022-08-22,19,M,55425,113.999,114.0,LF1,...,12.0,-0.340241,29.552181,0.0,0.0,0.0,843.14820,0.0,7.289444,159.775050

In [33]:
df_weather.head()

,UnitId,Name,Date,Hour,Temperature,Humidity,Dew,ApparentTemperature,Precipitation,Rain,Snow,SurfacePressure,Evapotranspiration,WindSpeed,WindDirection
0,917,حافظ,2021-03-21,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
1,917,حافظ,2021-03-21,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
2,917,حافظ,2021-03-21,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
3,917,حافظ,2021-03-21,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
4,917,حافظ,2021-03-21,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN

In [32]:
df_old[["PowerPlantCode", "UnitCode"]].drop_duplicates()

KeyError: "None of [Index(['PowerPlantCode', 'UnitCode'], dtype='object')] are in the [columns]"

In [26]:
def set_minus(df1, df2, column=None):
    if column is None:
        column = df1.columns.to_list()
    merged = df1.merge(df2, on=column, how='left', indicator=True)
    result = merged[merged['_merge'] == 'left_only'].drop('_merge', axis=1)
    return result


def equals(df1, df2):
    return set_minus(df1, df2).empty and set_minus(df2, df1).empty

In [27]:
def delete_C(df):
    df1 = df.copy()
    df1["code_e"] = df1["code"].copy()
    df1["code"] = df1["code"].apply(lambda x: x[1:] if x.startswith("C") else x)
    return df1

In [6]:
df_energy.head()

   DispPlantCode UnitCode              Name        Date  Hour  generation
0            104       S1  سيکل ترکيبي پرند  2021-03-21     1  129.671081
1            104       S1  سيکل ترکيبي پرند  2021-03-22     1    0.000000
2            104       S1  سيکل ترکيبي پرند  2021-03-23     1  150.046121
3            104       S1  سيکل ترکيبي پرند  2021-03-24     1  136.338788
4            104       S1  سيکل ترکيبي پرند  2021-03-25     1  139.025321

In [14]:
df_energy = df_energy.rename(columns={"DispPlantCode": "id", "UnitCode": "code", "Name": "name"})
df_energy.head()

    id code              name        Date  Hour  generation
0  104   S1  سيکل ترکيبي پرند  2021-03-21     1  129.671081
1  104   S1  سيکل ترکيبي پرند  2021-03-22     1    0.000000
2  104   S1  سيکل ترکيبي پرند  2021-03-23     1  150.046121
3  104   S1  سيکل ترکيبي پرند  2021-03-24     1  136.338788
4  104   S1  سيکل ترکيبي پرند  2021-03-25     1  139.025321

In [11]:
print(equals(df_old[["id", "code"]].drop_duplicates(), df_energy[["id", "code"]].drop_duplicates()))

False

In [12]:
set_minus(delete_C(df_energy)[["id", "code", "code_e"]].drop_duplicates(), df_new[["id", "code"]].drop_duplicates(),
          column=["id", "code"])

     id code code_e
0   104   S1     S1
1   104   S2     S2
2   104   S3     S3
9   111  G11    G11
10  111  G12    G12
11  111  G13    G13
12  111  G14    G14
13  111  G15    G15
14  111  G16    G16
15  111  G17    G17
16  111  G18    G18
17  111  G19    G19
18  111  G20    G20
19  111  G21    G21
20  111  G22    G22
21  111   S1     S1
22  111   S2     S2
23  111   S3     S3
24  111   S4     S4
25  111   S5     S5
26  111   S6     S6
27  149  G11    G11
28  149  G12    G12
29  149  G13    G13
30  149  G14    G14
31  149   S1     S1
32  149   S2     S2
33  232  G11    G11
34  232  G12    G12
35  232  G13    G13
36  232  G14    G14
37  232  G15    G15
38  232  G16    G16
39  232   S1     S1
40  232   S2     S2
41  232   S3     S3
44  365  G13    G13
45  365  G14    G14
47  365   S2     S2
61  515   S1     S1
68  636  G13    G13
69  636  G14    G14
70  636  G15    G15
71  636  G16    G16
72  636   S1     S1
73  636   S2     S2

In [271]:
set_minus(df_new[["id", "code"]].drop_duplicates(), df_energy[["id", "code"]].drop_duplicates(), column=["id", "code"])

Empty DataFrame
Columns: [id, code, code_e]
Index: []

In [16]:
set_minus(df_energy[["id", "code", "name"]].drop_duplicates(), df_old[["id", "code"]].drop_duplicates(),
          column=["id", "code"])

     id code                     name
44  365  G13  سيکل ترکيبي شهداي پيروز
45  365  G14  سيکل ترکيبي شهداي پيروز
47  365   S2  سيکل ترکيبي شهداي پيروز

just in df_energy()
	id	code	name
44	365	G13	سيکل ترکيبي شهداي پيروز
45	365	G14	سيکل ترکيبي شهداي پيروز
47	365	S2	سيکل ترکيبي شهداي پيروز

In [17]:
set_minus(df_old[["id", "code", "name"]].drop_duplicates(), df_energy[["id", "code"]].drop_duplicates(),
          column=["id", "code"])

      id code                name
50   422   S6       شهید منتظری 1
51   422   S4       شهید منتظری 1
52   422   S5       شهید منتظری 1
53   422   S3       شهید منتظری 1
54   422   S7       شهید منتظری 1
55   422   S8       شهید منتظری 1
56   422   S1       شهید منتظری 1
68   422   S2       شهید منتظری 1
69   503   S2               سبلان
70   503   S3               سبلان
99   515   S2  سیکل ترکیبی ارومیه
101  902   S2              عسلویه
103  515   S3  سیکل ترکیبی ارومیه

In [21]:
dd = df_old.dropna()
dd[["id", "code"]].drop_duplicates()

          id code
156      104  G13
157      104  G12
158      104  G11
16183    104   S2
16184    104   S1
...      ...  ...
1397345  917  G11
1451220  636  G16
1451222  636   S1
1531437  902  G16
1531438  902  G15

[95 rows x 2 columns]

In [19]:
df_new[["id", "code"]].drop_duplicates()

         id code
0       406  G11
34392   406  G12
46848   406  G13
59304   406  G14
71760   406  G15
84216   406  G16
96672   917  G11
131064  917  G12
143520  917  G13
155976  917  G14
168432  917  G15
180888  917  G16
193344  503  G11
227736  503  G12
240192  503  G13
252648  503  G14
265104  503  G15
277560  503  G16
290016  503   S1
299232  515  G11
333624  515  G12
346080  515  G13
358536  515  G14
370992  515  G15
383448  515  G16
395904  715  G11
430296  715  G12
442752  715  G13
455208  715  G14
467664  715  G15
480120  715  G16
492576  715   S1
505032  715   S2
517488  715   S3
523968  636  G11
558360  636  G12
570816  365  G11
605208  365  G12
617664  365   S1
630120  902  G11
664512  902  G12
676968  902  G13
689424  902  G14
701880  902  G15
714336  902  G16
726792  902   S1
738072  104  G11
772464  104  G12
784920  104  G13
797376  104  G14
809832  104  G15
822288  104  G16

In [261]:
df_selleroffer[["id", "name", "code"]][df_selleroffer["id"] == 365].drop_duplicates()

          id                  name code
1472288  365  شهدای پیروز - بهبهان  G11
1507784  365  شهدای پیروز - بهبهان  G12
1543281  365  شهدای پیروز - بهبهان   S1

In [262]:
set_minus(df_old[["id", "code"]].drop_duplicates(), df_commitment[["id", "code"]].drop_duplicates(),
          column=["id", "code"])

Empty DataFrame
Columns: [id, code]
Index: []

In [263]:
set_minus(df_commitment[["id", "code"]].drop_duplicates(), df_old[["id", "code"]].drop_duplicates(),
          column=["id", "code"])

Empty DataFrame
Columns: [id, code]
Index: []

In [264]:
df_weather2 = df_weather.rename(columns={"unitid": "id"})
set_minus(df_old[["id"]].drop_duplicates(), df_weather2[["id"]].drop_duplicates())

Empty DataFrame
Columns: [id]
Index: []

In [265]:
set_minus(df_weather2[["id"]].drop_duplicates(), df_old[["id"]].drop_duplicates())

Empty DataFrame
Columns: [id]
Index: []

In [266]:
df_selleroffer.head()

    id  name code        date  hour  declare
0  104  پرند  G11  2021-03-21     1    132.0
1  104  پرند  G11  2021-03-21     2    132.0
2  104  پرند  G11  2021-03-21     3    132.0
3  104  پرند  G11  2021-03-21     4    132.0
4  104  پرند  G11  2021-03-21     5    133.0

In [267]:
set_minus(df_old[["id", "code"]].drop_duplicates(),
          df_selleroffer[["id", "code"]].drop_duplicates())  # old = energy + 422

Empty DataFrame
Columns: [id, code]
Index: []

In [268]:
set_minus(df_selleroffer[["id", "code"]].drop_duplicates(),
          df_old[["id", "code"]].drop_duplicates())  # old = energy + 422

Empty DataFrame
Columns: [id, code]
Index: []

In [120]:
def get_null(df, df_name_code):
    infos = []
    for _, row in df_name_code.iterrows():
        name = row["name"]
        code = row["code"]
        inf = Data_selector(df).filter_name_code(name, code)
        g = (inf.isnull().sum() / len(inf)).astype(object)
        g.loc["name"] = name
        g.loc["code"] = code
        infos.append(g)
    df_infos = pd.DataFrame(infos)

    drop_cols = []
    for col in df_infos.columns:
        try:
            m = sum(df_infos[col])
            #print(col,m)
            if m == 0:
                print(col)
                drop_cols.append(col)
        except:
            pass
            #print(col)
    df_infos2 = df_infos.drop(columns=drop_cols)
    df_infos2.columns[(df_infos2 == 1).all()]

    return df_infos2

In [122]:
get_null(df_old, df_old_name_code)

id
date
hour
load_level
forecasted_load
required
wind_speed

,name,code,declared,status,generation,temp_sens,scadaf,temperature,humidity,dew,apparent_temperature,precipitation,rain,snow,surface_pressure,evapotranspiration,wind_direction
0,پرند,G12,0.000000,0.0,0.001923,0.100641,0.100641,0.004087,0.004087,0.004087,0.004087,1.0,0.004167,0.004167,0.004167,0.004087,0.004087
1,پرند,S1,0.000000,0.0,1.000000,0.100641,0.100641,0.004087,0.004087,0.004087,0.004087,1.0,0.004167,0.004167,0.004167,0.004087,0.004087
2,پرند,S3,0.000000,0.0,1.000000,0.100641,0.100641,0.004087,0.004087,0.004087,0.004087,1.0,0.004167,0.004167,0.004167,0.004087,0.004087
3,پرند,G13,0.000000,0.0,0.001923,0.100641,0.100641,0.004087,0.004087,0.004087,0.004087,1.0,0.004167,0.004167,0.004167,0.004087,0.004087
4,پرند,G15,0.000000,0.0,0.001923,0.100641,0.100641,0.004087,0.004087,0.004087,0.004087,1.0,0.004167,0.004167,0.004167,0.004087,0.004087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,سیکل ترکیبی ارومیه,S2,0.573394,0.0,1.000000,0.526376,0.526376,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
104,عسلویه,S2,1.000000,0.0,1.000000,0.051418,0.051418,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
105,سبلان,S2,1.000000,0.0,1.000000,0.847518,0.847518,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
106,سبلان,S3,1.000000,0.0,1.000000,0.662946,0.662946,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
107,سیکل ترکیبی ارومیه,S3,1.000000,0.0,1.000000,0.039062,0.039062,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000

In [123]:
def is_bigger(a, b1, b2):
    try:
        return a >= b1 and a <= b2
    except:
        return False


print("خانه‌هایی با مقدار 1:")
for index, row in df_infos2.iterrows():
    ones_in_row = []
    for col in df_infos2.columns:
        if col not in ['name', 'id'] and is_bigger(row[col], 1, 1):
            ones_in_row.append(col)

    if ones_in_row:
        print(f"{row['name']} {(22 - len(row['name'])) * ' '} {row['code']}, ستون‌ها: {', '.join(ones_in_row)}")

خانه‌هایی با مقدار 1:
پرند                    S1, ستون‌ها: generation, precipitation
پرند                    S3, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G16, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   S3, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   S2, ستون‌ها: generation, precipitation
قم                      G13, ستون‌ها: generation, precipitation
قم                      G12, ستون‌ها: generation, precipitation
گیلان                   G14, ستون‌ها: generation, precipitation
گیلان                   G13, ستون‌ها: generation, precipitation
گیلان                   G15, ستون‌ها: generation, precipitation
شهید منتظری 1           S4, ستون‌ها: generation, precipitation
شهید منتظری 1           S3, ستون‌ها: generation, precipitation
شهید منتظری 1           S5, ستون‌ها: generation, precipitation
سیکل ترکیبی ارومیه      S1, ستون‌ها: generation, precipitation
سیکل ترکیبی یزد         G14, ستون‌ها: generation, precipitation
سیکل ترکیبی یزد         G15, ستون‌ها: generation, precipitation
سیکل ترکیبی یزد         G13, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   S6, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G11, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G15, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G17, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G14, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   S4, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G21, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G18, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G13, ستون‌ها: generation, precipitation
قم                      G11, ستون‌ها: generation, precipitation
قم                      S1, ستون‌ها: generation, precipitation
قم                      G14, ستون‌ها: generation, precipitation
گیلان                   S1, ستون‌ها: generation, precipitation
گیلان                   G16, ستون‌ها: generation, precipitation
گیلان                   S2, ستون‌ها: generation, precipitation
شهید منتظری 1           S7, ستون‌ها: generation, precipitation
شهید منتظری 1           S1, ستون‌ها: generation, precipitation
شهید منتظری 1           S6, ستون‌ها: generation, precipitation
سیکل ترکیبی یزد         S1, ستون‌ها: generation, precipitation
سیکل ترکیبی یزد         S2, ستون‌ها: generation, precipitation
شهید منتظری 1           S8, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   S1, ستون‌ها: generation, precipitation
پرند                    S2, ستون‌ها: generation, precipitation
شهید منتظری 1           S2, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G22, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G19, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G12, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   G20, ستون‌ها: generation, precipitation
شهدای پاکدشت - دماوند   S5, ستون‌ها: generation, precipitation
قم                      S2, ستون‌ها: generation, precipitation
گیلان                   G12, ستون‌ها: generation, precipitation
گیلان                   G11, ستون‌ها: generation, precipitation
گیلان                   S3, ستون‌ها: generation, precipitation
سیکل ترکیبی یزد         G16, ستون‌ها: generation, precipitation
سیکل ترکیبی ارومیه      S2, ستون‌ها: generation, precipitation
عسلویه                  S2, ستون‌ها: declared, generation, precipitation
سبلان                   S2, ستون‌ها: declared, generation, precipitation
سبلان                   S3, ستون‌ها: declared, generation, precipitation
سیکل ترکیبی ارومیه      S3, ستون‌ها: declared, generation, precipitation

In [249]:
df_energy_name_code[["name", "code"]].drop_duplicates()

                    name code
0       سيکل ترکيبي پرند   S1
1433    سيکل ترکيبي پرند   S2
2866    سيکل ترکيبي پرند   S3
4299    سيکل ترکيبي پرند  G11
5732    سيکل ترکيبي پرند  G12
...                  ...  ...
130727  سيکل ترکيبي حافظ  G12
132160  سيکل ترکيبي حافظ  G13
133593  سيکل ترکيبي حافظ  G14
135026  سيکل ترکيبي حافظ  G15
136459  سيکل ترکيبي حافظ  G16

[98 rows x 2 columns]

In [251]:
delete_C(df_energy)

          id code              name        date  hour  generation code_e
0        104   S1  سيکل ترکيبي پرند  2021-03-21     1  129.671081     S1
1        104   S1  سيکل ترکيبي پرند  2021-03-22     1    0.000000     S1
2        104   S1  سيکل ترکيبي پرند  2021-03-23     1  150.046121     S1
3        104   S1  سيکل ترکيبي پرند  2021-03-24     1  136.338788     S1
4        104   S1  سيکل ترکيبي پرند  2021-03-25     1  139.025321     S1
...      ...  ...               ...         ...   ...         ...    ...
3309403  917  G16  سيکل ترکيبي حافظ  2025-02-20    24   48.907920    G16
3309404  917  G16  سيکل ترکيبي حافظ  2025-02-21    24    0.000000    G16
3309405  917  G16  سيکل ترکيبي حافظ  2025-02-22    24  122.459420    G16
3309406  917  G16  سيکل ترکيبي حافظ  2025-02-23    24   86.027730    G16
3309407  917  G16  سيکل ترکيبي حافظ  2025-02-24    24   91.663740    G16

[3309408 rows x 7 columns]

In [235]:
delete_C(df_energy_name_code)[["name", "code"]].drop_duplicates()

                    name code
0       سيکل ترکيبي پرند   S1
1433    سيکل ترکيبي پرند   S2
2866    سيکل ترکيبي پرند   S3
4299    سيکل ترکيبي پرند  G11
5732    سيکل ترکيبي پرند  G12
...                  ...  ...
130727  سيکل ترکيبي حافظ  G12
132160  سيکل ترکيبي حافظ  G13
133593  سيکل ترکيبي حافظ  G14
135026  سيکل ترکيبي حافظ  G15
136459  سيکل ترکيبي حافظ  G16

[98 rows x 2 columns]

In [246]:
df_energy_name_code

                    name code code_e
0       سيکل ترکيبي پرند   S1     S1
1433    سيکل ترکيبي پرند   S2     S2
2866    سيکل ترکيبي پرند   S3     S3
4299    سيکل ترکيبي پرند  G11    G11
5732    سيکل ترکيبي پرند  G12    G12
...                  ...  ...    ...
130727  سيکل ترکيبي حافظ  G12    G12
132160  سيکل ترکيبي حافظ  G13    G13
133593  سيکل ترکيبي حافظ  G14    G14
135026  سيکل ترکيبي حافظ  G15    G15
136459  سيکل ترکيبي حافظ  G16    G16

[98 rows x 3 columns]

In [245]:
df_energy["code_e"].drop_duplicates()

0         S1
1433      S2
2866      S3
4299     G11
5732     G12
7165     G13
8598     G14
10031    G15
11464    G16
21459    G17
22885    G18
24308    G19
25735    G20
27161    G21
28588    G22
34294     S4
35720     S5
37147     S6
Name: code_e, dtype: object

In [243]:
df_energy["code_e"]

0           S1
1           S1
2           S1
3           S1
4           S1
          ...
3309403    G16
3309404    G16
3309405    G16
3309406    G16
3309407    G16
Name: code_e, Length: 3309408, dtype: object